@HOSTAPI=http://agtmobile.agroterenas.com.br:8281

###

# @name login
POST {{HOSTAPI}}/agt-api-pims/autenticacao HTTP/1.1
content-Type: application/json

    {
        "username":"agtestimativa",
        "password":"5E30F86F9024CB774DF4D834C57AD9FE6EB0EE63432B454C3675071D603CB7F6"	
    }

@TOKEN = Bearer {{login.response.body.$.token}}

###

GET {{HOSTAPI}}/agt-api-pims/api/usuario/lista/all HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    


###

// TODO precisa dessa API
GET {{HOSTAPI}}/agt-api-pims/api/instancia/lista/all HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    

###

GET {{HOSTAPI}}/agt-api-pims/api/usuario/lista/usuario/instancia/all HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    


###

GET {{HOSTAPI}}/agt-api-pims/api/safra/instancia/NAMAR HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    

###

GET {{HOSTAPI}}/agt-api-pims/api/dispositivo/sequencia/aplicativo/idDispositivo/1/instancia/NAMAR/idAplicativo/96 HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    

###

POST {{HOSTAPI}}/agt-api-pims/api/dispositivo/registro HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    

{
  "cartaoSim": "teste123",
  "idAndroid": "teste123",
  "idDispositivo": 0,
  "imei": "teste123",
  "situacao": "A"
}

###

# Áreas Nivel3 por Safra
GET {{HOSTAPI}}/agt-api-pims/api/estimativa/consulta?instancia=NAMAR&cdSafra=22021 HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    

###

POST {{HOSTAPI}}/agt-api-pims/api/estimativa/insert HTTP/1.1
content-Type: application/json
authorization: {{TOKEN}}    

[
    {
        "cdEstagio": 2,
        "cdSafra": 22021,
        "cdTpPropr": 51,
        "cdUpnivel1": "201015",
        "cdUpnivel2": "  1088",
        "cdUpnivel3": "     1",
        "cdVaried": 330,
        "dtUltimoCorte": "2019-05-01",
        "instancia": "NAMAR",
        "precipitacao": 473.59999999999997,
        "qtAreaProd": 7.27,
        "producaoSafraAnt": 883.98,
        "sphenophous": 0,
        "tch0": 100,
        "tch1": null,
        "tch2": null,
        "tch3": null,
        "tch4": null,
        "cdFunc": 116670,
        "noBoletim": 10006,
        "noSeq": 1,
        "dispositivo": 1,
        "dtHistorico": "2020-08-13"
    },
  {
        "cdEstagio": 1,
        "cdSafra": 22021,
        "cdTpPropr": 51,
        "cdUpnivel1": "201015",
        "cdUpnivel2": "  1088",
        "cdUpnivel3": "    22",
        "cdVaried": 364,
        "dtUltimoCorte": "2019-03-26",
        "instancia": "NAMAR",
        "precipitacao": 814.8000000000001,
        "qtAreaProd": 1.34,
        "producaoSafraAnt": 70.16,
        "sphenophous": 0,
        "tch0": 23,
        "tch1": null,
        "tch2": null,
        "tch3": null,
        "tch4": null,
        "cdFunc": 116670,
        "noBoletim": 10006,
        "noSeq": 2,
        "dispositivo": 1,
        "dtHistorico": "2020-08-13"
    }
]

