name: apontamento
description: apontamento
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.2.4
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  dio: ^3.0.10
  sqflite: ^1.3.0
  package_info: ^0.4.3
  shared_preferences: ^0.5.10
  page_transition: ^1.1.6
  timeago: ^2.0.27
  simple_moment: ^1.0.6
  path_provider: ^1.6.14
  flutter_email_sender: ^3.0.1
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
