const tabelaEstimativa = '''
  CREATE TABLE apont_estimativa (
    dispositivo INTEGER NOT NULL,
    instancia TEXT NOT NULL,
    noBoletim INTEGER NOT NULL,
    noSeq INTEGER NOT NULL,
    cdSafra INTEGER,
    cdUpnivel1 TEXT NOT NULL,
    cdUpnivel2 TEXT NOT NULL,
    cdUpnivel3 TEXT NOT NULL,
    cdTpPropr INTEGER,
    deTpPropr TEXT,
    cdVaried INTEGER,
    deVaried TEXT,
    cdEstagio INTEGER,
    deEstagio TEXT,
    dtUltimoCorte TEXT, 
    precipitacao REAL,
    qtAreaProd REAL,
    producaoSafraAnt REAL,
    sphenophous REAL,
    tch0 REAL,
    tch1 REAL,
    tch2 REAL,
    tch3 REAL,
    tch4 REAL,
    tchAnoPassado REAL,
    tchAnoRetrasado REAL,
    cdFunc INTEGER,
    dtHistorico TEXT,
    status TEXT,
    dtStatus TEXT,
    PRIMARY KEY(dispositivo,instancia,noBoletim, noSeq, cdUpnivel1, cdUpnivel2, cdUpnivel3)
  )
''';
